// generated by lib/utils/02.languages-data.mjs

export const LANG_NAMES = [
  "angular-html",
  "angular-ts",
  "apache",
  "applescript",
  "asm",
  "astro",
  "awk",
  "bat",
  "batch",
  "c",
  "c#",
  "c++",
  "clarity",
  "clj",
  "clojure",
  "cmake",
  "codeowners",
  "coffee",
  "coffeescript",
  "common-lisp",
  "cpp",
  "cs",
  "csharp",
  "css",
  "csv",
  "diff",
  "docker",
  "dockerfile",
  "dotenv",
  "elisp",
  "elixir",
  "elm",
  "emacs-lisp",
  "erb",
  "erl",
  "erlang",
  "f#",
  "fish",
  "fs",
  "fsharp",
  "git-commit",
  "git-rebase",
  "gjs",
  "gleam",
  "glimmer-js",
  "glimmer-ts",
  "gnuplot",
  "go",
  "gql",
  "graphql",
  "groovy",
  "gts",
  "hack",
  "haml",
  "handlebars",
  "haskell",
  "hbs",
  "hs",
  "html",
  "html-derivative",
  "http",
  "ini",
  "java",
  "javascript",
  "jinja",
  "jison",
  "jl",
  "js",
  "json",
  "json5",
  "jsonc",
  "jsonl",
  "jsx",
  "julia",
  "kotlin",
  "kt",
  "kts",
  "latex",
  "less",
  "liquid",
  "lisp",
  "log",
  "logo",
  "lua",
  "luau",
  "make",
  "makefile",
  "markdown",
  "md",
  "mdx",
  "nginx",
  "objc",
  "objective-c",
  "objective-cpp",
  "ocaml",
  "perl",
  "php",
  "postcss",
  "prisma",
  "prolog",
  "properties",
  "proto",
  "puppet",
  "py",
  "python",
  "r",
  "racket",
  "rb",
  "regex",
  "regexp",
  "rs",
  "ruby",
  "rust",
  "sass",
  "scala",
  "scheme",
  "scss",
  "smalltalk",
  "solidity",
  "sparql",
  "spl",
  "splunk",
  "sql",
  "styl",
  "stylus",
  "svelte",
  "swift",
  "systemd",
  "tcl",
  "terminal",
  "text",
  "toml",
  "ts",
  "tsp",
  "tsx",
  "txt",
  "typescript",
  "typespec",
  "vue",
  "vue-html",
  "wasm",
  "xml",
  "yaml",
  "yml",
  "zig"
];
type NamesTuple = typeof LANG_NAMES;
export type LanguageAlias = NamesTuple[number];
export type LanguageName = 
  | "angular-html"
  | "angular-ts"
  | "apache"
  | "applescript"
  | "asm"
  | "astro"
  | "awk"
  | "bat"
  | "c"
  | "clarity"
  | "clojure"
  | "cmake"
  | "codeowners"
  | "coffee"
  | "common-lisp"
  | "cpp"
  | "csharp"
  | "css"
  | "csv"
  | "diff"
  | "docker"
  | "dotenv"
  | "elixir"
  | "elm"
  | "emacs-lisp"
  | "erb"
  | "erlang"
  | "fish"
  | "fsharp"
  | "git-commit"
  | "git-rebase"
  | "gleam"
  | "glimmer-js"
  | "glimmer-ts"
  | "gnuplot"
  | "go"
  | "graphql"
  | "groovy"
  | "hack"
  | "haml"
  | "handlebars"
  | "haskell"
  | "html"
  | "html-derivative"
  | "http"
  | "ini"
  | "java"
  | "javascript"
  | "jinja"
  | "jison"
  | "json"
  | "json5"
  | "jsonc"
  | "jsonl"
  | "jsx"
  | "julia"
  | "kotlin"
  | "latex"
  | "less"
  | "liquid"
  | "log"
  | "logo"
  | "lua"
  | "luau"
  | "make"
  | "markdown"
  | "mdx"
  | "nginx"
  | "objective-c"
  | "objective-cpp"
  | "ocaml"
  | "perl"
  | "php"
  | "postcss"
  | "prisma"
  | "prolog"
  | "proto"
  | "puppet"
  | "python"
  | "r"
  | "racket"
  | "regexp"
  | "ruby"
  | "rust"
  | "sass"
  | "scala"
  | "scheme"
  | "scss"
  | "smalltalk"
  | "solidity"
  | "sparql"
  | "splunk"
  | "sql"
  | "stylus"
  | "svelte"
  | "swift"
  | "systemd"
  | "tcl"
  | "toml"
  | "tsx"
  | "txt"
  | "typescript"
  | "typespec"
  | "vue"
  | "vue-html"
  | "wasm"
  | "xml"
  | "yaml"
  | "zig";
export type ScopeName = 
  | "text.html.derivative.ng"
  | "source.ts.ng"
  | "source.apacheconf"
  | "source.applescript"
  | "source.asm.x86_64"
  | "source.astro"
  | "source.awk"
  | "source.batchfile"
  | "source.c"
  | "source.clar"
  | "source.clojure"
  | "source.cmake"
  | "text.codeowners"
  | "source.coffee"
  | "source.commonlisp"
  | "source.cpp"
  | "source.cs"
  | "source.css"
  | "text.csv"
  | "source.diff"
  | "source.dockerfile"
  | "source.dotenv"
  | "source.elixir"
  | "source.elm"
  | "source.emacs.lisp"
  | "text.html.erb"
  | "source.erlang"
  | "source.fish"
  | "source.fsharp"
  | "text.git-commit"
  | "text.git-rebase"
  | "source.gleam"
  | "source.gjs"
  | "source.gts"
  | "source.gnuplot"
  | "source.go"
  | "source.graphql"
  | "source.groovy"
  | "source.hack"
  | "text.haml"
  | "text.html.handlebars"
  | "source.haskell"
  | "text.html.basic"
  | "text.html.derivative"
  | "source.http"
  | "source.ini"
  | "source.java"
  | "source.js"
  | "source.jinja"
  | "source.jison"
  | "source.json"
  | "source.json5"
  | "source.json.comments"
  | "source.json.lines"
  | "source.js.jsx"
  | "source.julia"
  | "source.kotlin"
  | "text.tex.latex"
  | "source.css.less"
  | "text.html.liquid"
  | "text.log"
  | "source.logo"
  | "source.lua"
  | "source.luau"
  | "source.makefile"
  | "text.html.markdown"
  | "source.mdx"
  | "source.nginx"
  | "source.objc"
  | "source.objcpp"
  | "source.ocaml"
  | "source.perl"
  | "source.php"
  | "source.css.postcss"
  | "source.prisma"
  | "source.prolog"
  | "source.proto"
  | "source.puppet"
  | "source.python"
  | "source.r"
  | "source.racket"
  | "source.regexp.python"
  | "source.ruby"
  | "source.rust"
  | "source.sass"
  | "source.scala"
  | "source.scheme"
  | "source.css.scss"
  | "source.smalltalk"
  | "source.solidity"
  | "source.sparql"
  | "source.splunk_search"
  | "source.sql"
  | "source.stylus"
  | "source.svelte"
  | "source.swift"
  | "source.systemd"
  | "source.tcl"
  | "source.toml"
  | "source.tsx"
  | "source.txt"
  | "source.ts"
  | "source.tsp"
  | "source.vue"
  | "text.html.vue-html"
  | "source.wat"
  | "text.xml"
  | "source.yaml"
  | "source.zig";

export type LanguageData = {
  id: LanguageName;
  embeddedScopes: ScopeName[];
};
  
export const aliasOrIdToScope: Record<LanguageAlias, ScopeName> = {
  "angular-html": "text.html.derivative.ng",
  "angular-ts": "source.ts.ng",
  "apache": "source.apacheconf",
  "applescript": "source.applescript",
  "asm": "source.asm.x86_64",
  "astro": "source.astro",
  "awk": "source.awk",
  "bat": "source.batchfile",
  "batch": "source.batchfile",
  "c": "source.c",
  "clarity": "source.clar",
  "clojure": "source.clojure",
  "clj": "source.clojure",
  "cmake": "source.cmake",
  "codeowners": "text.codeowners",
  "coffee": "source.coffee",
  "coffeescript": "source.coffee",
  "common-lisp": "source.commonlisp",
  "lisp": "source.commonlisp",
  "cpp": "source.cpp",
  "c++": "source.cpp",
  "csharp": "source.cs",
  "c#": "source.cs",
  "cs": "source.cs",
  "css": "source.css",
  "csv": "text.csv",
  "diff": "source.diff",
  "docker": "source.dockerfile",
  "dockerfile": "source.dockerfile",
  "dotenv": "source.dotenv",
  "elixir": "source.elixir",
  "elm": "source.elm",
  "emacs-lisp": "source.emacs.lisp",
  "elisp": "source.emacs.lisp",
  "erb": "text.html.erb",
  "erlang": "source.erlang",
  "erl": "source.erlang",
  "fish": "source.fish",
  "fsharp": "source.fsharp",
  "f#": "source.fsharp",
  "fs": "source.fsharp",
  "git-commit": "text.git-commit",
  "git-rebase": "text.git-rebase",
  "gleam": "source.gleam",
  "glimmer-js": "source.gjs",
  "gjs": "source.gjs",
  "glimmer-ts": "source.gts",
  "gts": "source.gts",
  "gnuplot": "source.gnuplot",
  "go": "source.go",
  "graphql": "source.graphql",
  "gql": "source.graphql",
  "groovy": "source.groovy",
  "hack": "source.hack",
  "haml": "text.haml",
  "handlebars": "text.html.handlebars",
  "hbs": "text.html.handlebars",
  "haskell": "source.haskell",
  "hs": "source.haskell",
  "html": "text.html.basic",
  "html-derivative": "text.html.derivative",
  "http": "source.http",
  "ini": "source.ini",
  "properties": "source.ini",
  "java": "source.java",
  "javascript": "source.js",
  "js": "source.js",
  "jinja": "source.jinja",
  "jison": "source.jison",
  "json": "source.json",
  "json5": "source.json5",
  "jsonc": "source.json.comments",
  "jsonl": "source.json.lines",
  "jsx": "source.js.jsx",
  "julia": "source.julia",
  "jl": "source.julia",
  "kotlin": "source.kotlin",
  "kt": "source.kotlin",
  "kts": "source.kotlin",
  "latex": "text.tex.latex",
  "less": "source.css.less",
  "liquid": "text.html.liquid",
  "log": "text.log",
  "logo": "source.logo",
  "lua": "source.lua",
  "luau": "source.luau",
  "make": "source.makefile",
  "makefile": "source.makefile",
  "markdown": "text.html.markdown",
  "md": "text.html.markdown",
  "mdx": "source.mdx",
  "nginx": "source.nginx",
  "objective-c": "source.objc",
  "objc": "source.objc",
  "objective-cpp": "source.objcpp",
  "ocaml": "source.ocaml",
  "perl": "source.perl",
  "php": "source.php",
  "postcss": "source.css.postcss",
  "prisma": "source.prisma",
  "prolog": "source.prolog",
  "proto": "source.proto",
  "puppet": "source.puppet",
  "python": "source.python",
  "py": "source.python",
  "r": "source.r",
  "racket": "source.racket",
  "regexp": "source.regexp.python",
  "regex": "source.regexp.python",
  "ruby": "source.ruby",
  "rb": "source.ruby",
  "rust": "source.rust",
  "rs": "source.rust",
  "sass": "source.sass",
  "scala": "source.scala",
  "scheme": "source.scheme",
  "scss": "source.css.scss",
  "smalltalk": "source.smalltalk",
  "solidity": "source.solidity",
  "sparql": "source.sparql",
  "splunk": "source.splunk_search",
  "spl": "source.splunk_search",
  "sql": "source.sql",
  "stylus": "source.stylus",
  "styl": "source.stylus",
  "svelte": "source.svelte",
  "swift": "source.swift",
  "systemd": "source.systemd",
  "tcl": "source.tcl",
  "toml": "source.toml",
  "tsx": "source.tsx",
  "txt": "source.txt",
  "typescript": "source.ts",
  "ts": "source.ts",
  "typespec": "source.tsp",
  "tsp": "source.tsp",
  "vue": "source.vue",
  "vue-html": "text.html.vue-html",
  "wasm": "source.wat",
  "xml": "text.xml",
  "yaml": "source.yaml",
  "yml": "source.yaml",
  "zig": "source.zig"
};
export const scopeToLanguageData: Record<ScopeName, LanguageData> = {
  "text.html.derivative.ng": {
    "id": "angular-html",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.ts.ng": {
    "id": "angular-ts",
    "embeddedScopes": []
  },
  "source.apacheconf": {
    "id": "apache",
    "embeddedScopes": []
  },
  "source.applescript": {
    "id": "applescript",
    "embeddedScopes": []
  },
  "source.asm.x86_64": {
    "id": "asm",
    "embeddedScopes": []
  },
  "source.astro": {
    "id": "astro",
    "embeddedScopes": [
      "source.json",
      "source.js",
      "source.ts",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.css.postcss",
      "source.tsx"
    ]
  },
  "source.awk": {
    "id": "awk",
    "embeddedScopes": []
  },
  "source.batchfile": {
    "id": "bat",
    "embeddedScopes": []
  },
  "source.c": {
    "id": "c",
    "embeddedScopes": []
  },
  "source.clar": {
    "id": "clarity",
    "embeddedScopes": []
  },
  "source.clojure": {
    "id": "clojure",
    "embeddedScopes": []
  },
  "source.cmake": {
    "id": "cmake",
    "embeddedScopes": []
  },
  "text.codeowners": {
    "id": "codeowners",
    "embeddedScopes": []
  },
  "source.coffee": {
    "id": "coffee",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.commonlisp": {
    "id": "common-lisp",
    "embeddedScopes": []
  },
  "source.cpp": {
    "id": "cpp",
    "embeddedScopes": [
      "source.regexp.python",
      "source.sql"
    ]
  },
  "source.cs": {
    "id": "csharp",
    "embeddedScopes": []
  },
  "source.css": {
    "id": "css",
    "embeddedScopes": []
  },
  "text.csv": {
    "id": "csv",
    "embeddedScopes": []
  },
  "source.diff": {
    "id": "diff",
    "embeddedScopes": []
  },
  "source.dockerfile": {
    "id": "docker",
    "embeddedScopes": []
  },
  "source.dotenv": {
    "id": "dotenv",
    "embeddedScopes": []
  },
  "source.elixir": {
    "id": "elixir",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.elm": {
    "id": "elm",
    "embeddedScopes": []
  },
  "source.emacs.lisp": {
    "id": "emacs-lisp",
    "embeddedScopes": []
  },
  "text.html.erb": {
    "id": "erb",
    "embeddedScopes": [
      "text.html.basic",
      "source.ruby"
    ]
  },
  "source.erlang": {
    "id": "erlang",
    "embeddedScopes": []
  },
  "source.fish": {
    "id": "fish",
    "embeddedScopes": []
  },
  "source.fsharp": {
    "id": "fsharp",
    "embeddedScopes": [
      "text.html.markdown"
    ]
  },
  "text.git-commit": {
    "id": "git-commit",
    "embeddedScopes": [
      "source.diff"
    ]
  },
  "text.git-rebase": {
    "id": "git-rebase",
    "embeddedScopes": []
  },
  "source.gleam": {
    "id": "gleam",
    "embeddedScopes": []
  },
  "source.gjs": {
    "id": "glimmer-js",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.css",
      "text.html.basic"
    ]
  },
  "source.gts": {
    "id": "glimmer-ts",
    "embeddedScopes": [
      "source.ts",
      "source.css",
      "source.js",
      "text.html.basic"
    ]
  },
  "source.gnuplot": {
    "id": "gnuplot",
    "embeddedScopes": []
  },
  "source.go": {
    "id": "go",
    "embeddedScopes": []
  },
  "source.graphql": {
    "id": "graphql",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.js.jsx",
      "source.tsx"
    ]
  },
  "source.groovy": {
    "id": "groovy",
    "embeddedScopes": []
  },
  "source.hack": {
    "id": "hack",
    "embeddedScopes": [
      "text.html.basic",
      "source.sql"
    ]
  },
  "text.haml": {
    "id": "haml",
    "embeddedScopes": [
      "source.ruby",
      "source.js",
      "source.sass",
      "source.coffee",
      "text.html.markdown",
      "source.css"
    ]
  },
  "text.html.handlebars": {
    "id": "handlebars",
    "embeddedScopes": [
      "text.html.basic",
      "source.css",
      "source.js",
      "source.yaml"
    ]
  },
  "source.haskell": {
    "id": "haskell",
    "embeddedScopes": []
  },
  "text.html.basic": {
    "id": "html",
    "embeddedScopes": [
      "source.js",
      "source.css"
    ]
  },
  "text.html.derivative": {
    "id": "html-derivative",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.http": {
    "id": "http",
    "embeddedScopes": [
      "source.json",
      "text.xml",
      "source.graphql"
    ]
  },
  "source.ini": {
    "id": "ini",
    "embeddedScopes": []
  },
  "source.java": {
    "id": "java",
    "embeddedScopes": []
  },
  "source.js": {
    "id": "javascript",
    "embeddedScopes": []
  },
  "source.jinja": {
    "id": "jinja",
    "embeddedScopes": []
  },
  "source.jison": {
    "id": "jison",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.json": {
    "id": "json",
    "embeddedScopes": []
  },
  "source.json5": {
    "id": "json5",
    "embeddedScopes": []
  },
  "source.json.comments": {
    "id": "jsonc",
    "embeddedScopes": []
  },
  "source.json.lines": {
    "id": "jsonl",
    "embeddedScopes": []
  },
  "source.js.jsx": {
    "id": "jsx",
    "embeddedScopes": []
  },
  "source.julia": {
    "id": "julia",
    "embeddedScopes": [
      "source.cpp",
      "source.python",
      "source.js",
      "source.r",
      "source.sql"
    ]
  },
  "source.kotlin": {
    "id": "kotlin",
    "embeddedScopes": []
  },
  "text.tex.latex": {
    "id": "latex",
    "embeddedScopes": [
      "source.css",
      "source.gnuplot",
      "source.haskell",
      "text.html.basic",
      "source.java",
      "source.julia",
      "source.js",
      "source.lua",
      "source.python",
      "source.ruby",
      "source.rust",
      "source.ts",
      "text.xml",
      "source.yaml",
      "source.scala"
    ]
  },
  "source.css.less": {
    "id": "less",
    "embeddedScopes": []
  },
  "text.html.liquid": {
    "id": "liquid",
    "embeddedScopes": [
      "text.html.basic",
      "source.css",
      "source.json",
      "source.js"
    ]
  },
  "text.log": {
    "id": "log",
    "embeddedScopes": []
  },
  "source.logo": {
    "id": "logo",
    "embeddedScopes": []
  },
  "source.lua": {
    "id": "lua",
    "embeddedScopes": [
      "source.c"
    ]
  },
  "source.luau": {
    "id": "luau",
    "embeddedScopes": []
  },
  "source.makefile": {
    "id": "make",
    "embeddedScopes": []
  },
  "text.html.markdown": {
    "id": "markdown",
    "embeddedScopes": [
      "source.css",
      "text.html.basic",
      "source.ini",
      "source.java",
      "source.lua",
      "source.makefile",
      "source.perl",
      "source.r",
      "source.ruby",
      "source.php",
      "source.sql",
      "text.xml",
      "source.yaml",
      "source.batchfile",
      "source.clojure",
      "source.coffee",
      "source.c",
      "source.cpp",
      "source.diff",
      "source.dockerfile",
      "text.git-commit",
      "text.git-rebase",
      "source.go",
      "source.groovy",
      "source.js",
      "source.json",
      "source.json.comments",
      "source.css.less",
      "source.objc",
      "source.swift",
      "source.css.scss",
      "source.python",
      "source.julia",
      "source.regexp.python",
      "source.rust",
      "source.scala",
      "source.ts",
      "source.tsx",
      "source.cs",
      "source.fsharp",
      "text.html.handlebars",
      "text.log",
      "source.erlang",
      "source.elixir",
      "text.tex.latex",
      "text.html.derivative"
    ]
  },
  "source.mdx": {
    "id": "mdx",
    "embeddedScopes": [
      "source.tsx",
      "source.toml",
      "source.yaml",
      "source.c",
      "source.clojure",
      "source.coffee",
      "source.cpp",
      "source.cs",
      "source.css",
      "source.diff",
      "source.dockerfile",
      "source.elixir",
      "source.elm",
      "source.erlang",
      "source.go",
      "source.graphql",
      "source.haskell",
      "text.html.basic",
      "source.ini",
      "source.java",
      "source.js",
      "source.json",
      "source.julia",
      "source.kotlin",
      "source.css.less",
      "source.lua",
      "source.makefile",
      "text.html.markdown",
      "source.objc",
      "source.perl",
      "source.python",
      "source.r",
      "source.ruby",
      "source.rust",
      "source.scala",
      "source.css.scss",
      "source.sql",
      "text.xml",
      "source.swift",
      "source.ts"
    ]
  },
  "source.nginx": {
    "id": "nginx",
    "embeddedScopes": [
      "source.lua"
    ]
  },
  "source.objc": {
    "id": "objective-c",
    "embeddedScopes": []
  },
  "source.objcpp": {
    "id": "objective-cpp",
    "embeddedScopes": []
  },
  "source.ocaml": {
    "id": "ocaml",
    "embeddedScopes": []
  },
  "source.perl": {
    "id": "perl",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.css",
      "source.js",
      "source.sql"
    ]
  },
  "source.php": {
    "id": "php",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.sql",
      "source.js",
      "source.json",
      "source.css"
    ]
  },
  "source.css.postcss": {
    "id": "postcss",
    "embeddedScopes": []
  },
  "source.prisma": {
    "id": "prisma",
    "embeddedScopes": []
  },
  "source.prolog": {
    "id": "prolog",
    "embeddedScopes": []
  },
  "source.proto": {
    "id": "proto",
    "embeddedScopes": []
  },
  "source.puppet": {
    "id": "puppet",
    "embeddedScopes": []
  },
  "source.python": {
    "id": "python",
    "embeddedScopes": []
  },
  "source.r": {
    "id": "r",
    "embeddedScopes": []
  },
  "source.racket": {
    "id": "racket",
    "embeddedScopes": []
  },
  "source.regexp.python": {
    "id": "regexp",
    "embeddedScopes": []
  },
  "source.ruby": {
    "id": "ruby",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.sql",
      "source.css",
      "source.c",
      "source.js",
      "source.lua"
    ]
  },
  "source.rust": {
    "id": "rust",
    "embeddedScopes": []
  },
  "source.sass": {
    "id": "sass",
    "embeddedScopes": []
  },
  "source.scala": {
    "id": "scala",
    "embeddedScopes": []
  },
  "source.scheme": {
    "id": "scheme",
    "embeddedScopes": []
  },
  "source.css.scss": {
    "id": "scss",
    "embeddedScopes": [
      "source.css"
    ]
  },
  "source.smalltalk": {
    "id": "smalltalk",
    "embeddedScopes": []
  },
  "source.solidity": {
    "id": "solidity",
    "embeddedScopes": []
  },
  "source.sparql": {
    "id": "sparql",
    "embeddedScopes": []
  },
  "source.splunk_search": {
    "id": "splunk",
    "embeddedScopes": []
  },
  "source.sql": {
    "id": "sql",
    "embeddedScopes": []
  },
  "source.stylus": {
    "id": "stylus",
    "embeddedScopes": []
  },
  "source.svelte": {
    "id": "svelte",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.coffee",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.css.postcss",
      "text.html.markdown"
    ]
  },
  "source.swift": {
    "id": "swift",
    "embeddedScopes": []
  },
  "source.systemd": {
    "id": "systemd",
    "embeddedScopes": []
  },
  "source.tcl": {
    "id": "tcl",
    "embeddedScopes": []
  },
  "source.toml": {
    "id": "toml",
    "embeddedScopes": []
  },
  "source.tsx": {
    "id": "tsx",
    "embeddedScopes": []
  },
  "source.txt": {
    "id": "txt",
    "embeddedScopes": []
  },
  "source.ts": {
    "id": "typescript",
    "embeddedScopes": []
  },
  "source.tsp": {
    "id": "typespec",
    "embeddedScopes": []
  },
  "source.vue": {
    "id": "vue",
    "embeddedScopes": [
      "text.html.basic",
      "text.html.markdown",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.js",
      "source.ts",
      "source.js.jsx",
      "source.tsx",
      "source.coffee",
      "source.json",
      "source.json.comments",
      "source.json5",
      "source.yaml",
      "source.toml",
      "source.graphql",
      "text.html.derivative"
    ]
  },
  "text.html.vue-html": {
    "id": "vue-html",
    "embeddedScopes": [
      "source.vue",
      "source.js"
    ]
  },
  "source.wat": {
    "id": "wasm",
    "embeddedScopes": []
  },
  "text.xml": {
    "id": "xml",
    "embeddedScopes": [
      "source.java"
    ]
  },
  "source.yaml": {
    "id": "yaml",
    "embeddedScopes": []
  },
  "source.zig": {
    "id": "zig",
    "embeddedScopes": []
  }
};
